# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none
pr: none

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'c49dfe0d-0ee7-4dbd-88b6-b0f14e219dc9'
  imageRepository: 'mail-mcp'
  containerRegistry: 'mailassist.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

- stage: Deploy
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: AzureRmWebAppDeployment@5
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'ME-MngEnvMCAP723313-v-jiabinzhou-1(20c2ec34-c954-4b17-83ce-ffb7bae3146e)'
        appType: 'webAppContainer'
        WebAppName: 'mail-assist-ews'
        DockerNamespace: 'mailassist.azurecr.io'
        DockerRepository: 'mail-mcp'
        DockerImageTag: '$(tag)'
